import { StyleSheet } from "react-native"

import { fonts } from "@/lib/theme"

export const calendarAgendaStyles = StyleSheet.create({
  agenda: { position: "relative" },
  period: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
  },
  periodTitle: { flex: 1, gap: 2 },
  eyebrow: { fontFamily: fonts.monoMedium, fontSize: 9, letterSpacing: 1.1 },
  month: {
    fontFamily: fonts.heading,
    fontSize: 16,
    textTransform: "capitalize",
  },
  today: {
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderRadius: 10,
  },
  todayText: { fontFamily: fonts.sansSemibold, fontSize: 11 },
  periodButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  state: {
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 20,
  },
  stateText: { fontFamily: fonts.sans, fontSize: 13, textAlign: "center" },
  error: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    margin: 12,
    padding: 13,
    borderRadius: 12,
  },
  errorCopy: { flex: 1, gap: 2 },
  errorTitle: { fontFamily: fonts.sansSemibold, fontSize: 13 },
  errorAction: { fontFamily: fonts.sans, fontSize: 11 },
  day: {
    minHeight: 88,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  dateRail: { width: 54, paddingTop: 2 },
  dayNumber: { fontFamily: fonts.headingBold, fontSize: 25, lineHeight: 27 },
  dayLabel: {
    marginTop: 3,
    fontFamily: fonts.monoMedium,
    fontSize: 9,
    letterSpacing: 0.5,
  },
  events: { flex: 1, gap: 7 },
  event: {
    minHeight: 58,
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderLeftWidth: 3,
    borderRadius: 10,
  },
  time: { fontFamily: fonts.monoMedium, fontSize: 10 },
  eventTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  eventTitle: {
    flex: 1,
    fontFamily: fonts.sansSemibold,
    fontSize: 13,
    lineHeight: 17,
  },
  cancelledTitle: { textDecorationLine: "line-through" },
  syncing: {
    position: "absolute",
    top: 70,
    right: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  syncingText: { fontFamily: fonts.sansMedium, fontSize: 10 },
})
